### ISSUE TITLE
can't specify custom template

### ISSUE THREAD

**Issue by insanum** [urosjarc/gitbook-plugin-build#7]
Custom template file isn't picked up from book.json config. 

Line #80 in helper.js needs to resolve the filename path with `this.getSrc()` as follows:

```
fileStat = fs.statSync(this.getSrc(this.config.template));
```
https://github.com/urosjarc/gitbook-plugin-build/blob/master/src/helper.js#L80

**Comment by urosjarc** [comment]
The link that you are pointing at is joust checking if template exist, this is location where template is being parsed: [helper.js#L91](https://github.com/urosjarc/gitbook-plugin-build/blob/master/src/helper.js#L91).

Can you provide whole log file created with this command:
```
gitbook build --debug > gitbook-debug.txt
```

It will really helped me if you can provide minimum working example in which you duplicate your problem.
